### ISSUE TITLE
`npm audit` periodic flow failing

### ISSUE THREAD

**Issue by ssmall** [GoogleCloudPlatform/cloud-run-anthos-reference-web-app#99]
[Example failure](https://github.com/GoogleCloudPlatform/cloud-run-anthos-reference-web-app/runs/834993495?check_suite_focus=true)

```
(node:2982) UnhandledPromiseRejectionWarning: Error: spawnSync npm ENOBUFS
    at Object.spawnSync (internal/child_process.js:1041:20)
    at Object.spawnSync (child_process.js:607:24)
    at Audit.<anonymous> (/home/runner/work/_actions/oke-py/npm-audit-action/v1.5.0/dist/index.js:1134:48)
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/oke-py/npm-audit-action/v1.5.0/dist/index.js:1116:71
    at new Promise (<anonymous>)
    at module.exports.50.__awaiter (/home/runner/work/_actions/oke-py/npm-audit-action/v1.5.0/dist/index.js:1112:12)
    at Audit.run (/home/runner/work/_actions/oke-py/npm-audit-action/v1.5.0/dist/index.js:1132:16)
    at /home/runner/work/_actions/oke-py/npm-audit-action/v1.5.0/dist/index.js:3321:19
    at Generator.next (<anonymous>)
(node:2982) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2982) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ssmall** [comment]
Opened https://github.com/oke-py/npm-audit-action/issues/66

**Comment by ssmall** [comment]
Bumping this down to p2 as the flow is no longer failing: https://github.com/GoogleCloudPlatform/cloud-run-anthos-reference-web-app/runs/854749531?check_suite_focus=true
